import app, { PartnerReferrals } from "./admin-ops-v2.js";
export { PartnerReferrals };

const ROOT="/kaizuro-admin", STORE="kaizuro-partner-submissions";
const HOSTS=new Set(["kaizuro.com","www.kaizuro.com","portal.kaizuro.com"]);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const lower=v=>String(v||"").trim().toLowerCase();
const now=()=>new Date().toISOString();
const money=v=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(Number(v||0));
const day=v=>{try{return new Date(v).toLocaleDateString("en-AU",{day:"numeric",month:"short",year:"numeric"})}catch{return"—"}};
function db(env){return env.PARTNER_REFERRALS.get(env.PARTNER_REFERRALS.idFromName(STORE));}
async function all(env,t){try{return await db(env).listAll(t)}catch{return[]}}
async function save(env,r){return db(env).createSubmission({...r,createdAt:r.createdAt||now()});}
function latest(rows,key){const m=new Map();for(const r of rows){const k=key(r);if(k&&!m.has(k))m.set(k,r)}return m;}
function id(p){return `${p}-${Date.now().toString(36)}-${crypto.randomUUID().slice(0,8)}`;}
function resp(s,status=200){return new Response(s,{status,headers:{"Content-Type":"text/html; charset=UTF-8","Cache-Control":"no-store","X-Robots-Tag":"noindex,nofollow,noarchive"}})}
function redir(r,p){return Response.redirect(new URL(p,r.url),303)}
function validOrigin(r){const o=r.headers.get("Origin");return !o||o===new URL(r.url).origin;}
async function authed(r,env,ctx){const u=new URL(r.url);u.pathname=ROOT;u.search="";return (await app.fetch(new Request(u,{method:"GET",headers:r.headers}),env,ctx)).status===200;}
async function shell(r,env,ctx){const u=new URL(r.url);u.pathname=`${ROOT}/dealers`;u.search="";return app.fetch(new Request(u,{method:"GET",headers:r.headers}),env,ctx);}
async function render(r,env,ctx,title,heading,copy,body,active){const b=await shell(r,env,ctx);if(b.status!==200)return b;return new HTMLRewriter().on(".top b",{element(e){e.setInnerContent(esc(title))}}).on(".content",{element(e){e.setInnerContent(`<section class="hero"><div><p class="eyebrow">KAIZURO Network Control</p><h1>${heading}</h1><p>${copy}</p></div></section>${body}`,{html:true})}}).on("aside nav .nav",{element(e){const href=e.getAttribute("href")||"";if(href.endsWith(`/${active}`))e.setAttribute("class","nav active")}}).transform(b);}
async function log(env,partner,action,contextType,contextRef,details=""){await save(env,{id:id("KZAUD"),type:"admin-activity",partnerId:partner||"network",action,contextType,contextRef,details,actor:"KAIZURO Admin"});}

async function leads(r,env,ctx){const [ls,ss,mm,accounts]=await Promise.all([all(env,"referral"),all(env,"lead-status"),all(env,"lead-admin-meta"),all(env,"account")]),status=latest(ss,x=>String(x.leadRef||x.leadId||"")),meta=latest(mm,x=>String(x.leadRef||""));const body=`<section class="panel kzv2-section"><div class="kzv2-actions" style="justify-content:space-between"><div><h2>Network leads</h2><p>Every dealer lead with KAIZURO follow-up ownership and commercial value.</p></div></div><div class="table-wrap"><table class="kzv2-table"><thead><tr><th>Lead</th><th>Customer</th><th>Dealer</th><th>Product</th><th>Stage</th><th>Next action</th><th>Follow-up</th><th>Value</th><th></th></tr></thead><tbody>${ls.slice(0,500).map(x=>{const m=meta.get(String(x.id))||{},s=status.get(String(x.id))?.status||x.status||"New",a=accounts.find(a=>[a.partnerId,a.email,a.username,a.dealerName].some(v=>lower(v)===lower(x.partnerId)||lower(v)===lower(x.partnerName))),dealer=a?.businessName||a?.dealerName||a?.contactName||x.partnerName||x.partnerId||"Dealer";return `<tr><td><b>${esc(x.id)}</b><br><small>${esc(day(x.createdAt))}</small></td><td>${esc(x.customerName||"—")}<br><small>${esc(x.customerEmail||x.customerMobile||"")}</small></td><td>${esc(dealer)}</td><td>${esc(x.productInterest||"—")}</td><td>${esc(s)}</td><td>${esc(m.nextAction||"—")}</td><td>${esc(m.followUpAt?day(m.followUpAt):"—")}</td><td>${m.expectedValue?money(m.expectedValue):"—"}</td><td><a class="btn light" href="${ROOT}/lead?ref=${encodeURIComponent(x.id)}">Manage</a></td></tr>`}).join("")}</tbody></table></div></section>`;return render(r,env,ctx,"Leads","Turn every lead<br>into a managed next action.","KAIZURO can see dealer progress, follow-up, ownership, expected value and lost reasons across the network.",body,"leads");}

async function orders(r,env,ctx){const [orders,meta,accounts]=await Promise.all([all(env,"sale"),all(env,"order-admin-meta"),all(env,"account")]),mm=latest(meta,x=>String(x.orderRef||"")),revenue=orders.reduce((s,x)=>s+Number(x.amount||x.revenue||0),0),pending=orders.filter(x=>lower(mm.get(String(x.id))?.paymentStatus||x.paymentStatus||"")&&!['paid','complete'].includes(lower(mm.get(String(x.id))?.paymentStatus||x.paymentStatus))).length;const body=`<div class="kzv2-grid"><div class="kzv2-card"><small>Attributed orders</small><strong>${orders.length}</strong></div><div class="kzv2-card"><small>Attributed revenue</small><strong>${money(revenue)}</strong></div><div class="kzv2-card"><small>Payment attention</small><strong>${pending}</strong></div><div class="kzv2-card"><small>Average order</small><strong>${money(orders.length?revenue/orders.length:0)}</strong></div></div><section class="panel kzv2-section"><h2>Orders + payments</h2><p>Real sale records only. Operational payment and fulfilment metadata can be managed here.</p><div class="table-wrap"><table class="kzv2-table"><thead><tr><th>Order</th><th>Dealer</th><th>Customer</th><th>Product</th><th>Value</th><th>Payment</th><th>Fulfilment</th><th></th></tr></thead><tbody>${orders.map(x=>{const m=mm.get(String(x.id))||{},a=accounts.find(a=>lower(a.partnerId||a.email)===lower(x.partnerId)),dealer=a?.businessName||a?.dealerName||x.partnerName||x.partnerId||"Dealer";return `<tr><td><b>${esc(x.id)}</b><br><small>${esc(day(x.createdAt))}</small></td><td>${esc(dealer)}</td><td>${esc(x.customerName||x.customer||"—")}</td><td>${esc(x.product||x.productInterest||"—")}</td><td>${money(x.amount||x.revenue||0)}</td><td>${esc(m.paymentStatus||x.paymentStatus||"Not set")}</td><td>${esc(m.fulfilmentStatus||x.fulfilmentStatus||"Not set")}</td><td><a class="btn light" href="${ROOT}/order?ref=${encodeURIComponent(x.id)}">Manage</a></td></tr>`}).join("")||`<tr><td colspan="8">No attributed orders yet.</td></tr>`}</tbody></table></div></section>`;return render(r,env,ctx,"Orders","See the commercial outcome,<br>not just the lead.","Orders, payments, fulfilment and dealer economics linked back to the dealer record.",body,"orders");}

async function order(r,env,ctx){const ref=new URL(r.url).searchParams.get("ref")||"",orders=await all(env,"sale"),x=orders.find(o=>String(o.id)===ref);if(!x)return resp("Order not found",404);const mm=latest(await all(env,"order-admin-meta"),m=>String(m.orderRef||"")),m=mm.get(ref)||{};const body=`<div class="kzv2-toolbar"><a class="btn light" href="${ROOT}/orders">Back to orders</a></div><div class="grid2"><section class="panel kzv2-section"><h2>${esc(ref)}</h2><p>${esc(x.customerName||x.customer||"Customer")}<br>${esc(x.product||x.productInterest||"—")} · ${money(x.amount||x.revenue||0)}</p></section><section class="panel kzv2-section"><h2>Order operations</h2><form class="kzv2-form" method="post" action="${ROOT}/order/meta"><input type="hidden" name="order" value="${esc(ref)}"><input type="hidden" name="partner" value="${esc(x.partnerId||"")}"><div class="kzv2-two"><label>Payment status<select name="paymentStatus">${["Not set","Pending","Paid","Refunded","Cancelled"].map(v=>`<option ${v===(m.paymentStatus||"Not set")?"selected":""}>${v}</option>`).join("")}</select></label><label>Fulfilment<select name="fulfilmentStatus">${["Not set","Pending","Processing","Shipped","Delivered","Cancelled"].map(v=>`<option ${v===(m.fulfilmentStatus||"Not set")?"selected":""}>${v}</option>`).join("")}</select></label></div><label>Tracking / reference<input name="tracking" value="${esc(m.tracking||"")}"></label><label>Internal order note<textarea name="notes">${esc(m.notes||"")}</textarea></label><button class="btn">Save order</button></form></section></div>`;return render(r,env,ctx,"Order","Control payment<br>and fulfilment status.","Operational metadata attached to the real attributed order.",body,"orders");}

async function marketing(r,env,ctx){const accounts=await all(env,"account"),body=`<section class="panel kzv2-section"><h2>Dealer marketing network</h2><p>Dealer codes and tracked links ready for campaign attribution.</p><div class="table-wrap"><table class="kzv2-table"><thead><tr><th>Dealer</th><th>Code</th><th>Tracked link</th><th>Status</th></tr></thead><tbody>${accounts.map(a=>{const code=a.referralCode||a.partnerCode||a.assignedPartnerId||"Not configured";return `<tr><td>${esc(a.businessName||a.dealerName||a.contactName||a.email)}</td><td><b>${esc(code)}</b></td><td>${code!=="Not configured"?`<code>${esc(`https://kaizuro.com/?dealer=${code}`)}</code>`:"—"}</td><td>${esc(a.status||"Active")}</td></tr>`}).join("")}</tbody></table></div></section>`;return render(r,env,ctx,"Marketing","Make every dealer<br>measurable.","Dealer attribution codes and tracked campaign links across the KAIZURO network.",body,"marketing");}

async function academy(r,env,ctx){const [accounts,completion]=await Promise.all([all(env,"account"),all(env,"academy-completion")]),modules=["ASSAULT","HALO","Engineering Story","Customer Qualification","Selling KAIZURO"],body=`<section class="panel kzv2-section"><h2>Dealer Academy</h2><p>Training and certification status across the dealer network.</p><div class="table-wrap"><table class="kzv2-table"><thead><tr><th>Dealer</th><th>Completed</th><th>Certification</th><th>Progress</th></tr></thead><tbody>${accounts.map(a=>{const p=String(a.partnerId||a.email||""),done=new Set(completion.filter(x=>lower(x.partnerId)===lower(p)).map(x=>x.module||x.moduleId)),n=modules.filter(m=>done.has(m)).length;return `<tr><td>${esc(a.businessName||a.dealerName||a.contactName||a.email)}</td><td>${n}/${modules.length}</td><td>${n===modules.length?`<span class="kzv2-pill green">KAIZURO Certified Dealer</span>`:`<span class="kzv2-pill">In progress</span>`}</td><td>${Math.round(n/modules.length*100)}%</td></tr>`}).join("")}</tbody></table></div></section>`;return render(r,env,ctx,"Academy","Know who can sell<br>the KAIZURO story properly.","Training completion and certification status across the dealer network.",body,"academy");}

async function post(r,env,ctx,path){if(!validOrigin(r)||!(await authed(r,env,ctx)))return resp("Unauthorized",403);const f=await r.formData();if(path==="order/meta"){const order=String(f.get("order")||""),partner=String(f.get("partner")||"");await save(env,{id:id("KZOM"),type:"order-admin-meta",partnerId:partner||"network",orderRef:order,paymentStatus:String(f.get("paymentStatus")||"Not set"),fulfilmentStatus:String(f.get("fulfilmentStatus")||"Not set"),tracking:String(f.get("tracking")||""),notes:String(f.get("notes")||"")});await log(env,partner||"network","Order operations updated","order",order);return redir(r,`${ROOT}/order?ref=${encodeURIComponent(order)}`)}return null;}

export default {async fetch(r,env,ctx){const u=new URL(r.url),path=u.pathname.replace(/\/$/,"");if(!HOSTS.has(u.hostname.toLowerCase())||!path.startsWith(ROOT))return app.fetch(r,env,ctx);if(r.method==="POST"){const x=await post(r,env,ctx,path.slice(ROOT.length+1));if(x)return x;return app.fetch(r,env,ctx)}if(r.method!=="GET"||!(await authed(r,env,ctx)))return app.fetch(r,env,ctx);if(path===`${ROOT}/leads`)return leads(r,env,ctx);if(path===`${ROOT}/orders`)return orders(r,env,ctx);if(path===`${ROOT}/order`)return order(r,env,ctx);if(path===`${ROOT}/marketing`)return marketing(r,env,ctx);if(path===`${ROOT}/academy`)return academy(r,env,ctx);const response=await app.fetch(r,env,ctx);if(response.status===200&&(response.headers.get("Content-Type")||"").includes("text/html"))return new HTMLRewriter().on("aside nav",{element(e){const html=e.getAttribute("data-kz-v3");if(!html){e.append(`<a class="nav" href="${ROOT}/marketing"><span>Marketing</span><small></small></a><a class="nav" href="${ROOT}/academy"><span>Academy</span><small></small></a>`,{html:true});e.setAttribute("data-kz-v3","1")}}}).transform(response);return response;}};
