import app, { PartnerReferrals } from "./admin-ops-v4.js";
export { PartnerReferrals };

const ADMIN="/kaizuro-admin", PORTAL="/partners/portal", STORE="kaizuro-partner-submissions";
const HOSTS=new Set(["kaizuro.com","www.kaizuro.com","portal.kaizuro.com"]);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const lower=v=>String(v||"").trim().toLowerCase();
const now=()=>new Date().toISOString();
const day=v=>{try{return new Date(v).toLocaleDateString("en-AU",{day:"numeric",month:"short",year:"numeric"})}catch{return"—"}};
const money=v=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(Number(v||0));
function db(env){return env.PARTNER_REFERRALS.get(env.PARTNER_REFERRALS.idFromName(STORE));}
async function all(env,t){try{return await db(env).listAll(t)}catch{return[]}}
async function list(env,p,t){try{return await db(env).listForPartner(String(p),t)}catch{return[]}}
async function save(env,r){return db(env).createSubmission({...r,createdAt:r.createdAt||now()});}
function latest(rows,key){const m=new Map();for(const r of rows){const k=key(r);if(k&&!m.has(k))m.set(k,r)}return m;}
function id(p){return `${p}-${Date.now().toString(36)}-${crypto.randomUUID().slice(0,8)}`;}
function resp(s,status=200){return new Response(s,{status,headers:{"Content-Type":"text/html; charset=UTF-8","Cache-Control":"no-store, no-cache, must-revalidate, max-age=0","X-Robots-Tag":"noindex,nofollow,noarchive"}})}
function redir(r,p){return Response.redirect(new URL(p,r.url).toString(),303)}
function validOrigin(r){const o=r.headers.get("Origin");return !o||o===new URL(r.url).origin;}
function cookieEmail(r){const c=(r.headers.get("Cookie")||"").split(";").map(x=>x.trim()).find(x=>x.startsWith("kz_partner="));if(!c)return"";try{return lower(decodeURIComponent(c.split("=").slice(1).join("=")).split("|")[0])}catch{return""}}
function accountName(a){return a?.businessName||a?.dealerName||a?.contactName||a?.email||"Dealer";}
function accountKey(a){return String(a?.partnerId||a?.email||a?.username||"");}
function accountMatch(a,v){const q=lower(v);return !!q&&[a.partnerId,a.email,a.username,a.assignedPartnerId,a.referralCode,a.partnerCode,a.dealerCode,a.dealerName,a.businessName,a.contactName].some(x=>lower(x)===q);}
async function adminAuthed(r,env,ctx){const u=new URL(r.url);u.pathname=ADMIN;u.search="";return (await app.fetch(new Request(u,{method:"GET",headers:r.headers}),env,ctx)).status===200;}
async function dealerCtx(r,env,ctx){const email=cookieEmail(r);if(!email)return null;const probe=new URL(r.url);probe.pathname=`${PORTAL}/account`;probe.search="";const verified=await app.fetch(new Request(probe,{method:"GET",headers:r.headers}),env,ctx);if(verified.status!==200)return null;const rows=await list(env,email,"account");return{email,partnerId:email,account:rows[0]||{partnerId:email,email,dealerName:email}};}
async function adminShell(r,env,ctx){const u=new URL(r.url);u.pathname=`${ADMIN}/dealers`;u.search="";return app.fetch(new Request(u,{method:"GET",headers:r.headers}),env,ctx);}
async function dealerShell(r,env,ctx){const u=new URL(r.url);u.pathname=`${PORTAL}/account`;u.search="";return app.fetch(new Request(u,{method:"GET",headers:r.headers}),env,ctx);}
function adminStyles(){return `<style id="kz-v5">.kz5-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1px;background:#d1d2ce;border:1px solid #d1d2ce;margin-top:18px}.kz5-card{background:#fff;padding:18px}.kz5-card small{display:block;color:#777;font-size:11px;text-transform:uppercase}.kz5-card strong{display:block;margin-top:15px;font-size:28px;font-weight:400}.kz5-table{width:100%;border-collapse:collapse;background:#fff}.kz5-table th,.kz5-table td{padding:11px;border-bottom:1px solid #ddd;text-align:left;font-size:13px;vertical-align:top}.kz5-table th{font-size:11px;color:#777;text-transform:uppercase}.kz5-form{display:grid;gap:12px}.kz5-form label{display:grid;gap:6px;font-size:12px;font-weight:600}.kz5-form input,.kz5-form select,.kz5-form textarea{width:100%;min-height:42px;padding:9px;border:1px solid #c6c8c9;background:#fff;font:inherit;font-size:14px}.kz5-form textarea{min-height:110px}.kz5-two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.kz5-health{display:inline-flex;padding:5px 8px;font-size:11px;font-weight:700;text-transform:uppercase}.kz5-green{background:#e4f1e8;color:#276542}.kz5-watch{background:#f5edd7;color:#785e1f}.kz5-risk{background:#f1e5e5;color:#873f3f}.kz5-actions{display:flex;gap:6px;flex-wrap:wrap}.kz5-search{display:flex;gap:8px;margin:16px 0}.kz5-search input{flex:1;min-height:44px;padding:10px;border:1px solid #bbb;font-size:14px}.kz5-thread{display:grid;gap:10px}.kz5-msg{padding:14px;background:#fff;border:1px solid #ddd}.kz5-msg small{color:#777}.kz5-empty{padding:24px;border:1px dashed #bbb;text-align:center;color:#777}@media(max-width:700px){.kz5-grid,.kz5-two{grid-template-columns:1fr}}</style>`;}
async function renderAdmin(r,env,ctx,title,heading,copy,body,active){const b=await adminShell(r,env,ctx);if(b.status!==200)return b;return new HTMLRewriter().on("head",{element(e){e.append(adminStyles(),{html:true})}}).on(".top b",{element(e){e.setInnerContent(esc(title))}}).on(".content",{element(e){e.setInnerContent(`<section class="hero"><div><p class="eyebrow">KAIZURO Network Control</p><h1>${heading}</h1><p>${copy}</p></div></section>${body}`,{html:true})}}).on("aside nav",{element(e){e.append(`<a class="nav ${active==="paperwork"?"active":""}" href="${ADMIN}/paperwork"><span>Paperwork</span><small></small></a><a class="nav ${active==="search"?"active":""}" href="${ADMIN}/search"><span>Search</span><small></small></a><a class="nav ${active==="health"?"active":""}" href="${ADMIN}/health"><span>Dealer Health</span><small></small></a>`,{html:true})}}).transform(b);}
async function renderDealer(r,env,ctx,title,heading,copy,body,active){const b=await dealerShell(r,env,ctx);if(b.status!==200)return b;return new HTMLRewriter().on("head",{element(e){e.append(adminStyles(),{html:true})}}).on(".top b",{element(e){e.setInnerContent(esc(title))}}).on(".content",{element(e){e.setInnerContent(`<section class="hero"><div><p class="eyebrow">KAIZURO Dealer Network</p><h1>${heading}</h1><p>${copy}</p></div></section>${body}`,{html:true})}}).on("aside nav",{element(e){e.append(`<a class="nav ${active==="paperwork"?"active":""}" href="${PORTAL}/paperwork"><span>Paperwork</span><small></small></a><a class="nav ${active==="notifications"?"active":""}" href="${PORTAL}/notifications"><span>Notifications</span><small></small></a>`,{html:true})}}).transform(b);}
async function audit(env,partner,action,contextType,contextRef,details=""){await save(env,{id:id("KZAUD"),type:"admin-activity",partnerId:partner||"network",action,contextType,contextRef,details,actor:"KAIZURO Admin"});}

const FORM_TYPES=["Dealer Agreement","Territory / Exclusivity Acknowledgment","Pricing Terms","Marketing Consent","Payment / Bank Details","Compliance Declaration","Special Commercial Terms"];
async function paperworkAdmin(r,env,ctx){const [accounts,forms]=await Promise.all([all(env,"account"),all(env,"dealer-paperwork")]),fm=latest(forms,x=>`${lower(x.partnerId)}|${lower(x.formType)}`);const rows=[];for(const a of accounts){const p=accountKey(a);for(const type of FORM_TYPES){const f=fm.get(`${lower(p)}|${lower(type)}`);rows.push({a,p,type,f});}}const submitted=rows.filter(x=>x.f?.status==="Submitted"||x.f?.status==="Accepted").length;const body=`<div class="kz5-grid"><div class="kz5-card"><small>Dealers</small><strong>${accounts.length}</strong></div><div class="kz5-card"><small>Required forms</small><strong>${rows.length}</strong></div><div class="kz5-card"><small>Submitted / Accepted</small><strong>${submitted}</strong></div><div class="kz5-card"><small>Outstanding</small><strong>${rows.length-submitted}</strong></div></div><section class="panel" style="margin-top:18px"><h2>Paperwork register</h2><p>Online dealer agreements and operational paperwork. No file upload required.</p><div class="table-wrap"><table class="kz5-table"><thead><tr><th>Dealer</th><th>Form</th><th>Status</th><th>Signed / Submitted</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${esc(accountName(x.a))}</b><br><small>${esc(x.a.email||"")}</small></td><td>${esc(x.type)}</td><td>${esc(x.f?.status||"Not started")}</td><td>${esc(x.f?.acceptedBy||x.f?.submittedBy||"—")}${x.f?.createdAt?`<br><small>${day(x.f.createdAt)}</small>`:""}</td><td><a class="btn light" href="${ADMIN}/dealer?partner=${encodeURIComponent(x.p)}">Dealer</a></td></tr>`).join("")}</tbody></table></div></section>`;return renderAdmin(r,env,ctx,"Paperwork","Contracts without<br>paperwork chaos.","Dealer agreements, territory acknowledgments, pricing terms and compliance are completed online and stored against each dealer.",body,"paperwork");}

function healthFor(a,{leads=[],statuses=[],tasks=[],support=[],paperwork=[],academy=[]}){const p=lower(accountKey(a)),issues=[];const dealerLeads=leads.filter(x=>lower(x.partnerId)===p);const sm=latest(statuses,x=>String(x.leadRef||x.leadId||""));if(dealerLeads.some(x=>!['won','lost'].includes(lower(sm.get(String(x.id))?.status||x.status))&&Date.now()-new Date(x.createdAt||0).getTime()>7*86400000))issues.push("Stale leads");if(tasks.some(x=>lower(x.partnerId)===p&&!x.completed&&x.dueAt&&new Date(x.dueAt)<new Date()))issues.push("Overdue tasks");if(support.some(x=>lower(x.partnerId)===p&&lower(x.status||"open")!=="resolved"))issues.push("Open support");const pf=paperwork.filter(x=>lower(x.partnerId)===p);if(!pf.some(x=>x.formType==="Dealer Agreement"&&['Submitted','Accepted'].includes(x.status)))issues.push("Agreement missing");const ac=academy.filter(x=>lower(x.partnerId)===p);if(ac.length<5)issues.push("Academy incomplete");if(!a.region&&!a.location)issues.push("Territory missing");if(!a.email)issues.push("Email missing");return{issues,status:issues.length>=3?"At Risk":issues.length?"Watch":"Green"};}
async function healthAdmin(r,env,ctx){const [accounts,leads,statuses,tasks,support,paperwork,academy]=await Promise.all(["account","referral","lead-status","dealer-task","support","dealer-paperwork","academy-completion"].map(t=>all(env,t)));const context={leads,statuses,tasks,support,paperwork,academy},rows=accounts.map(a=>({a,...healthFor(a,context)}));const body=`<section class="panel" style="margin-top:18px"><h2>Dealer health + data quality</h2><p>Green means no current management exceptions. Watch and At Risk identify where KAIZURO should intervene.</p><div class="table-wrap"><table class="kz5-table"><thead><tr><th>Dealer</th><th>Health</th><th>Issues</th><th>Quick actions</th></tr></thead><tbody>${rows.map(x=>`<tr><td><a href="${ADMIN}/dealer?partner=${encodeURIComponent(accountKey(x.a))}"><b>${esc(accountName(x.a))}</b></a><br><small>${esc(x.a.email||"")}</small></td><td><span class="kz5-health ${x.status==="Green"?"kz5-green":x.status==="Watch"?"kz5-watch":"kz5-risk"}">${x.status}</span></td><td>${x.issues.length?esc(x.issues.join(" · ")):"No current issues"}</td><td><div class="kz5-actions"><a class="btn light" href="${ADMIN}/email?partner=${encodeURIComponent(accountKey(x.a))}">Email</a><a class="btn light" href="${ADMIN}/dealer?partner=${encodeURIComponent(accountKey(x.a))}">Profile</a><a class="btn light" href="${ADMIN}/communications">Log contact</a></div></td></tr>`).join("")}</tbody></table></div></section>`;return renderAdmin(r,env,ctx,"Dealer Health","See risk before<br>it becomes churn.","Dealer health combines follow-up discipline, support, paperwork, Academy and data quality into a practical management view.",body,"health");}

async function searchAdmin(r,env,ctx){const q=lower(new URL(r.url).searchParams.get("q")||"");const [accounts,leads,orders,support]=await Promise.all(["account","referral","sale","support"].map(t=>all(env,t)));const matches=(...vals)=>q&&vals.some(v=>lower(v).includes(q));const results=[];for(const a of accounts)if(matches(a.dealerName,a.businessName,a.contactName,a.email,a.assignedPartnerId,a.referralCode))results.push(["Dealer",accountName(a),a.email||a.assignedPartnerId,`${ADMIN}/dealer?partner=${encodeURIComponent(accountKey(a))}`]);for(const x of leads)if(matches(x.id,x.customerName,x.customerEmail,x.customerMobile,x.partnerName,x.productInterest))results.push(["Lead",x.customerName||x.id,x.id,`${ADMIN}/lead?ref=${encodeURIComponent(x.id)}`]);for(const x of orders)if(matches(x.id,x.customerName,x.customer,x.product,x.partnerName))results.push(["Order",x.customerName||x.id,x.id,`${ADMIN}/order?ref=${encodeURIComponent(x.id)}`]);for(const x of support)if(matches(x.id,x.partnerName,x.customerReference,x.requestType,x.details))results.push(["Support",x.partnerName||x.id,x.id,`${ADMIN}/support`]);const body=`<section class="panel" style="margin-top:18px"><h2>Global search</h2><form class="kz5-search" method="get"><input name="q" value="${esc(new URL(r.url).searchParams.get("q")||"")}" placeholder="Dealer, contact, code, lead, customer, order or support reference"><button class="btn">Search</button></form>${q?`<div class="table-wrap"><table class="kz5-table"><thead><tr><th>Type</th><th>Name</th><th>Reference</th><th></th></tr></thead><tbody>${results.slice(0,200).map(x=>`<tr><td>${esc(x[0])}</td><td><b>${esc(x[1])}</b></td><td>${esc(x[2]||"")}</td><td><a class="btn light" href="${esc(x[3])}">Open</a></td></tr>`).join("")||`<tr><td colspan="4">No matches.</td></tr>`}</tbody></table></div>`:`<div class="kz5-empty">Search the whole KAIZURO dealer network from one place.</div>`}</section>`;return renderAdmin(r,env,ctx,"Search","Find anything<br>in seconds.","Search dealer identities, codes, customers, leads, orders and support records from one Admin screen.",body,"search");}

async function dealerPaperwork(r,env,ctx,dctx){const forms=await list(env,dctx.partnerId,"dealer-paperwork"),fm=latest(forms,x=>lower(x.formType));const selected=new URL(r.url).searchParams.get("form")||"Dealer Agreement",f=fm.get(lower(selected))||{};const body=`<div class="grid2"><section class="panel" style="margin-top:18px"><h2>My paperwork</h2><p>Complete KAIZURO agreements and commercial paperwork online.</p><div class="table-wrap"><table class="kz5-table"><thead><tr><th>Form</th><th>Status</th><th></th></tr></thead><tbody>${FORM_TYPES.map(t=>{const x=fm.get(lower(t));return `<tr><td>${esc(t)}</td><td>${esc(x?.status||"Not started")}</td><td><a class="btn light" href="${PORTAL}/paperwork?form=${encodeURIComponent(t)}">Open</a></td></tr>`}).join("")}</tbody></table></div></section><section class="panel" style="margin-top:18px"><h2>${esc(selected)}</h2><form class="kz5-form" method="post" action="${PORTAL}/paperwork/save"><input type="hidden" name="formType" value="${esc(selected)}"><label>Business / dealer name<input value="${esc(accountName(dctx.account))}" disabled></label><label>Terms / information<textarea name="details" required>${esc(f.details||"")}</textarea></label><div class="kz5-two"><label>Accepted / submitted by<input name="acceptedBy" required value="${esc(f.acceptedBy||dctx.account.contactName||"")}"></label><label>Status<select name="status"><option ${f.status==="Draft"?"selected":""}>Draft</option><option ${f.status==="Submitted"?"selected":""}>Submitted</option><option ${f.status==="Accepted"?"selected":""}>Accepted</option></select></label></div><label style="display:flex;grid-template-columns:auto 1fr;align-items:center"><input type="checkbox" name="confirm" value="yes" required style="width:18px"> I confirm the information above is accurate and I am authorised to submit it for this dealer.</label><button class="btn">Save paperwork</button></form></section></div>`;return renderDealer(r,env,ctx,"Paperwork","Complete agreements<br>online.","No printing or document uploads. Your KAIZURO paperwork is stored securely against your dealer record.",body,"paperwork");}

async function dealerNotifications(r,env,ctx,dctx){const [notes,tasks,support,alloc,leads,lmeta,paperwork]=await Promise.all(["dealer-notification","dealer-task","support","allocation-request","referral","lead-admin-meta","dealer-paperwork"].map(t=>list(env,dctx.partnerId,t))),lm=latest(lmeta,x=>String(x.leadRef||""));const items=[];for(const n of notes)if(!n.dismissed)items.push([n.createdAt,n.title||"KAIZURO update",n.message||"",n.link||PORTAL]);for(const t of tasks)if(!t.completed)items.push([t.dueAt||t.createdAt,t.title||"Action required",t.nextAction||"",`${PORTAL}/account`]);for(const s of support)if(lower(s.status||"open")!=="resolved")items.push([s.createdAt,"Support request open",s.requestType||s.details||s.id,`${PORTAL}/support-thread?ref=${encodeURIComponent(s.id)}`]);for(const a of alloc)if(['approved','reserved','shipped'].includes(lower(a.status)))items.push([a.createdAt,`Allocation ${a.status}`,a.product||a.id,`${PORTAL}/allocation`]);for(const l of leads){const m=lm.get(String(l.id))||{};if(m.followUpAt&&new Date(m.followUpAt)<new Date())items.push([m.followUpAt,"Lead follow-up due",`${l.customerName||l.id} · ${m.nextAction||"Follow up"}`,`${PORTAL}/leads`]);}if(!paperwork.some(x=>x.formType==="Dealer Agreement"&&['Submitted','Accepted'].includes(x.status)))items.push([now(),"Dealer Agreement required","Complete your KAIZURO Dealer Agreement.",`${PORTAL}/paperwork?form=${encodeURIComponent("Dealer Agreement")}`]);items.sort((a,b)=>String(b[0]).localeCompare(String(a[0])));const body=`<div class="kz5-grid"><div class="kz5-card"><small>Action required</small><strong>${items.length}</strong></div><div class="kz5-card"><small>Open support</small><strong>${support.filter(x=>lower(x.status||"open")!=="resolved").length}</strong></div><div class="kz5-card"><small>Open tasks</small><strong>${tasks.filter(x=>!x.completed).length}</strong></div><div class="kz5-card"><small>Paperwork</small><strong>${paperwork.length}/${FORM_TYPES.length}</strong></div></div><section class="panel" style="margin-top:18px"><h2>Notifications + action required</h2><div class="kz5-thread">${items.map(x=>`<div class="kz5-msg"><small>${esc(day(x[0]))}</small><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p><a class="btn light" href="${esc(x[3])}">Open</a></div>`).join("")||`<div class="kz5-empty">Nothing needs your attention.</div>`}</div></section>`;return renderDealer(r,env,ctx,"Notifications","Know what KAIZURO<br>needs from you.","Leads, support, allocation, paperwork and dealer actions in one queue.",body,"notifications");}

async function supportThread(r,env,ctx,dctx){const ref=new URL(r.url).searchParams.get("ref")||"",support=await list(env,dctx.partnerId,"support"),ticket=support.find(x=>String(x.id)===ref);if(!ticket)return resp("Support request not found",404);const messages=(await list(env,dctx.partnerId,"support-message")).filter(x=>String(x.supportRef)===ref).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));const body=`<div class="grid2"><section class="panel" style="margin-top:18px"><h2>${esc(ref)}</h2><p><b>${esc(ticket.requestType||"Support")}</b><br>${esc(ticket.details||"")}</p><p>Status: ${esc(ticket.status||"Open")}</p><a class="btn light" href="${PORTAL}/support">Back to support</a></section><section class="panel" style="margin-top:18px"><h2>Conversation</h2><div class="kz5-thread">${messages.map(m=>`<div class="kz5-msg"><small>${esc(day(m.createdAt))} · ${esc(m.author||"Dealer")}</small><p>${esc(m.message)}</p></div>`).join("")||`<div class="kz5-empty">No replies yet.</div>`}</div><form class="kz5-form" method="post" action="${PORTAL}/support-message" style="margin-top:16px"><input type="hidden" name="ref" value="${esc(ref)}"><label>Reply<textarea name="message" required></textarea></label><button class="btn">Send reply</button></form></section></div>`;return renderDealer(r,env,ctx,"Support","One support request,<br>one conversation.","Keep every KAIZURO support exchange attached to the original request.",body,"support");}

async function adminSupportThread(r,env,ctx){const ref=new URL(r.url).searchParams.get("ref")||"",support=await all(env,"support"),ticket=support.find(x=>String(x.id)===ref);if(!ticket)return resp("Support request not found",404);const messages=(await all(env,"support-message")).filter(x=>String(x.supportRef)===ref).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));const body=`<div class="grid2"><section class="panel" style="margin-top:18px"><h2>${esc(ref)}</h2><p><b>${esc(ticket.partnerName||ticket.partnerId)}</b><br>${esc(ticket.requestType||"")}<br>${esc(ticket.details||"")}</p><a class="btn light" href="${ADMIN}/support">Back to support</a></section><section class="panel" style="margin-top:18px"><h2>Support thread</h2><div class="kz5-thread">${messages.map(m=>`<div class="kz5-msg"><small>${esc(day(m.createdAt))} · ${esc(m.author||"KAIZURO")}</small><p>${esc(m.message)}</p></div>`).join("")||`<div class="kz5-empty">No replies yet.</div>`}</div><form class="kz5-form" method="post" action="${ADMIN}/support-message" style="margin-top:16px"><input type="hidden" name="ref" value="${esc(ref)}"><input type="hidden" name="partner" value="${esc(ticket.partnerId)}"><label>Reply<textarea name="message" required></textarea></label><button class="btn">Send reply</button></form></section></div>`;return renderAdmin(r,env,ctx,"Support Thread","Keep support<br>in one conversation.","Every reply stays attached to the dealer and original support reference.",body,"support");}

async function postAdmin(r,env,ctx,path){if(!validOrigin(r)||!(await adminAuthed(r,env,ctx)))return resp("Unauthorized",403);const f=await r.formData();if(path==="support-message"){const ref=String(f.get("ref")||""),partner=String(f.get("partner")||""),message=String(f.get("message")||"").trim();if(!message)return resp("Message required",400);await save(env,{id:id("KZSM"),type:"support-message",partnerId:partner,supportRef:ref,message,author:"KAIZURO Admin"});await save(env,{id:id("KZNT"),type:"dealer-notification",partnerId:partner,title:"KAIZURO replied to support",message:`Support ${ref} has a new reply.`,link:`${PORTAL}/support-thread?ref=${encodeURIComponent(ref)}`});await audit(env,partner,"Support reply sent","support",ref);return redir(r,`${ADMIN}/support-thread?ref=${encodeURIComponent(ref)}`)}return null;}
async function postDealer(r,env,ctx,dctx,path){if(!validOrigin(r))return resp("Unauthorized",403);const f=await r.formData();if(path==="paperwork/save"){const formType=String(f.get("formType")||""),status=String(f.get("status")||"Draft"),acceptedBy=String(f.get("acceptedBy")||"").trim(),details=String(f.get("details")||"").trim();if(!FORM_TYPES.includes(formType)||!acceptedBy||!details||String(f.get("confirm")||"")!=="yes")return resp("Required paperwork fields are missing",400);await save(env,{id:id("KZPW"),type:"dealer-paperwork",partnerId:dctx.partnerId,partnerName:accountName(dctx.account),formType,status,acceptedBy,details,acceptedAt:status==="Accepted"?now():""});await audit(env,dctx.partnerId,`${formType} ${status.toLowerCase()}`,"paperwork",formType);return redir(r,`${PORTAL}/paperwork?form=${encodeURIComponent(formType)}`)}if(path==="support-message"){const ref=String(f.get("ref")||""),message=String(f.get("message")||"").trim();if(!message)return resp("Message required",400);await save(env,{id:id("KZSM"),type:"support-message",partnerId:dctx.partnerId,supportRef:ref,message,author:dctx.account.contactName||accountName(dctx.account)});await audit(env,dctx.partnerId,"Dealer replied to support","support",ref);return redir(r,`${PORTAL}/support-thread?ref=${encodeURIComponent(ref)}`)}return null;}

export default {async fetch(r,env,ctx){const u=new URL(r.url),host=u.hostname.toLowerCase(),path=u.pathname.replace(/\/$/,"");if(!HOSTS.has(host))return app.fetch(r,env,ctx);
 if(path.startsWith(ADMIN)){if(r.method==="POST"){const x=await postAdmin(r,env,ctx,path.slice(ADMIN.length+1));if(x)return x;return app.fetch(r,env,ctx)}if(r.method==="GET"&&await adminAuthed(r,env,ctx)){if(path===`${ADMIN}/paperwork`)return paperworkAdmin(r,env,ctx);if(path===`${ADMIN}/health`)return healthAdmin(r,env,ctx);if(path===`${ADMIN}/search`)return searchAdmin(r,env,ctx);if(path===`${ADMIN}/support-thread`)return adminSupportThread(r,env,ctx);const base=await app.fetch(r,env,ctx);if(base.status===200&&(base.headers.get("Content-Type")||"").includes("text/html")){return new HTMLRewriter().on("aside nav",{element(e){e.append(`<a class="nav" href="${ADMIN}/paperwork"><span>Paperwork</span><small></small></a><a class="nav" href="${ADMIN}/search"><span>Search</span><small></small></a><a class="nav" href="${ADMIN}/health"><span>Dealer Health</span><small></small></a>`,{html:true})}}).transform(base)}return base}return app.fetch(r,env,ctx)}
 if(path.startsWith(PORTAL)){const dctx=await dealerCtx(r,env,ctx);if(!dctx)return app.fetch(r,env,ctx);if(r.method==="POST"){const x=await postDealer(r,env,ctx,dctx,path.slice(PORTAL.length+1));if(x)return x;return app.fetch(r,env,ctx)}if(r.method==="GET"){if(path===`${PORTAL}/paperwork`)return dealerPaperwork(r,env,ctx,dctx);if(path===`${PORTAL}/notifications`)return dealerNotifications(r,env,ctx,dctx);if(path===`${PORTAL}/support-thread`)return supportThread(r,env,ctx,dctx);const base=await app.fetch(r,env,ctx);if(base.status===200&&(base.headers.get("Content-Type")||"").includes("text/html")){return new HTMLRewriter().on("aside nav",{element(e){e.append(`<a class="nav" href="${PORTAL}/paperwork"><span>Paperwork</span><small></small></a><a class="nav" href="${PORTAL}/notifications"><span>Notifications</span><small></small></a>`,{html:true})}}).transform(base)}return base}}
 return app.fetch(r,env,ctx);}};
