import app, { PartnerReferrals } from "./admin-visible-communications.js";
export { PartnerReferrals };

const ROOT="/kaizuro-admin";
const STORE="kaizuro-partner-submissions";
const HOSTS=new Set(["kaizuro.com","www.kaizuro.com","portal.kaizuro.com"]);
const LIFECYCLE=["Application","Approved","Onboarding","Active","Growth","At Risk","Suspended"];
const TIERS=["Authorised Dealer","Select Dealer","Premier Dealer"];
const APP_STATES=["Pending","Approved","More information required","Declined"];
const ONBOARD=["Agreement signed","Account created","Pricing confirmed","Academy completed","Marketing assets supplied","Initial allocation requested","First order","First lead","First sale"];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const lower=v=>String(v||"").trim().toLowerCase();
const now=()=>new Date().toISOString();
const money=v=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(Number(v||0));
const fmt=v=>{try{return new Date(v).toLocaleString("en-AU",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"})}catch{return"—"}};
const day=v=>{try{return new Date(v).toLocaleDateString("en-AU",{day:"numeric",month:"short",year:"numeric"})}catch{return"—"}};
function db(env){return env.PARTNER_REFERRALS.get(env.PARTNER_REFERRALS.idFromName(STORE));}
async function all(env,type){try{return await db(env).listAll(type)}catch{return[]}}
async function save(env,row){return db(env).createSubmission({...row,createdAt:row.createdAt||now()});}
function latest(rows,key){const m=new Map();for(const r of rows){const k=key(r);if(k&&!m.has(k))m.set(k,r)}return m;}
function id(prefix){return `${prefix}-${Date.now().toString(36)}-${crypto.randomUUID().slice(0,8)}`;}
function partnerKey(a){return String(a?.partnerId||a?.username||a?.email||"");}
function dealerName(a){return a?.businessName||a?.dealerName||a?.contactName||a?.email||"Dealer";}
function dealerContact(a){return a?.contactName||a?.dealerName||a?.businessName||a?.email||"Dealer";}
function dealerEmail(a){return String(a?.email||a?.username||"");}
function matches(a,v){const p=lower(v);return !!p&&[a.partnerId,a.username,a.email,a.assignedPartnerId,a.referralCode,a.partnerCode,a.dealerCode,a.dealerName,a.businessName,a.contactName].some(x=>lower(x)===p);}
async function accounts(env){return all(env,"account");}
async function accountFor(env,v){const rows=await accounts(env);if(lower(v)==="kz-au-001")return rows.find(a=>lower(a.email)==="w3protocol@proton.me")||null;return rows.find(a=>matches(a,v))||null;}
async function authed(request,env,ctx){const u=new URL(request.url);u.pathname=ROOT;u.search="";const r=await app.fetch(new Request(u,{method:"GET",headers:request.headers}),env,ctx);return r.status===200;}
async function base(request,env,ctx){const u=new URL(request.url);u.pathname=`${ROOT}/dealers`;u.search="";return app.fetch(new Request(u,{method:"GET",headers:request.headers}),env,ctx);}
function resp(s,status=200){return new Response(s,{status,headers:{"Content-Type":"text/html; charset=UTF-8","Cache-Control":"no-store, no-cache, must-revalidate, max-age=0","X-Robots-Tag":"noindex,nofollow,noarchive"}})}
function redir(request,path){return Response.redirect(new URL(path,request.url).toString(),303)}
function validOrigin(r){const o=r.headers.get("Origin");return !o||o===new URL(r.url).origin;}
function styles(){return `<style id="kz-admin-v2-css">
.kzv2-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.kzv2-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1px;background:#d1d2ce;border:1px solid #d1d2ce;margin-top:18px}.kzv2-card{background:#fff;padding:18px;min-height:112px}.kzv2-card small{display:block;color:#777;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.05em}.kzv2-card strong{display:block;font-size:28px;font-weight:400;margin-top:18px}.kzv2-tabs{display:flex;gap:6px;flex-wrap:wrap;margin:18px 0}.kzv2-tabs a{padding:9px 11px;border:1px solid #cfd0cc;background:#fff;text-decoration:none;font-size:12px}.kzv2-section{margin-top:18px}.kzv2-list{display:grid}.kzv2-row{display:grid;grid-template-columns:150px 1fr auto;gap:14px;padding:13px 0;border-bottom:1px solid #ddd;align-items:start}.kzv2-row small{color:#777}.kzv2-row p{margin:4px 0 0;font-size:13px;color:#555}.kzv2-form{display:grid;gap:12px}.kzv2-form label{display:grid;gap:6px;font-size:12px;font-weight:600}.kzv2-form input,.kzv2-form select,.kzv2-form textarea{width:100%;min-height:42px;padding:9px;border:1px solid #c6c8c9;background:#fff;font:inherit;font-size:14px}.kzv2-form textarea{min-height:100px}.kzv2-two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.kzv2-pill{display:inline-flex;padding:5px 8px;background:#e7e7e3;font-size:11px;font-weight:700;text-transform:uppercase}.kzv2-pill.red{background:#f1e5e5;color:#873f3f}.kzv2-pill.green{background:#e4f1e8;color:#276542}.kzv2-check{display:flex;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid #e2e2de}.kzv2-check input{width:18px;height:18px}.kzv2-muted{color:#777}.kzv2-empty{padding:28px;border:1px dashed #bbb;background:#f3f3ef;color:#777;text-align:center}.kzv2-nav-badge{font-size:11px!important}.kzv2-priority-high{color:#873f3f;font-weight:700}.kzv2-overdue{background:#f7e8e8}.kzv2-progress{height:7px;background:#ddd;margin-top:8px}.kzv2-progress span{display:block;height:100%;background:#111}.kzv2-score{font-size:34px;font-weight:400}.kzv2-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.kzv2-toolbar a{font-size:12px}.kzv2-table{width:100%;border-collapse:collapse;background:#fff}.kzv2-table th,.kzv2-table td{padding:11px;border-bottom:1px solid #ddd;text-align:left;font-size:13px;vertical-align:top}.kzv2-table th{font-size:11px;color:#777;text-transform:uppercase;letter-spacing:.05em}.kzv2-table small{font-size:11px;color:#777}.kzv2-anchor{font-weight:600;text-decoration:underline;text-underline-offset:3px}@media(max-width:1000px){.kzv2-grid{grid-template-columns:1fr 1fr}}@media(max-width:700px){.kzv2-grid,.kzv2-two{grid-template-columns:1fr}.kzv2-row{grid-template-columns:1fr;gap:5px}}
</style>`;}
async function counts(env){const [a,apps,leads,orders,alloc,sup,tasks]=await Promise.all(["account","application","referral","sale","allocation-request","support","dealer-task"].map(t=>all(env,t)));const openTasks=tasks.filter(t=>!t.completed).length;return{dealers:a.length,applications:apps.length,leads:leads.length,orders:orders.length,allocation:alloc.length,support:sup.length,tasks:openTasks};}
function nav(c,active){const items=[["overview","Overview","Live"],["attention","Attention",c.tasks],["dealers","Dealers",c.dealers],["applications","Applications",c.applications],["leads","Leads",c.leads],["orders","Orders",c.orders],["allocation","Allocation",c.allocation],["inventory","Inventory","2"],["products","Products","2"],["support","Support",c.support],["territories","Territories",""],["activity","Activity","Live"]];return items.map(([id,label,n])=>`<a class="nav ${active===id?"active":""}" href="${ROOT}/${id==="overview"?"":id}"><span>${label}</span><small class="kzv2-nav-badge">${esc(n)}</small></a>`).join("");}
async function render(request,env,ctx,{active,title,heading,copy,body}){const b=await base(request,env,ctx);if(b.status!==200)return b;const c=await counts(env);return new HTMLRewriter().on("head",{element(e){e.append(styles(),{html:true})}}).on("aside nav",{element(e){e.setInnerContent(nav(c,active),{html:true})}}).on(".top b",{element(e){e.setInnerContent(esc(title),{html:true})}}).on(".content",{element(e){e.setInnerContent(`<section class="hero"><div><p class="eyebrow">KAIZURO Network Control</p><h1>${heading}</h1><p>${copy}</p></div></section>${body}`,{html:true})}}).transform(b);}
async function data(env){const types=["account","application","referral","lead-status","sale","allocation-request","support","product-config","dealer-task","dealer-note","dealer-meta","dealer-onboarding","dealer-document","dealer-communication","admin-activity","application-decision","lead-admin-meta","order-admin-meta"];
 const r={};await Promise.all(types.map(async t=>r[t]=await all(env,t)));return r;}
function currentMap(rows,key){return latest(rows,key);}
function metaFor(rows,partner){return currentMap(rows,x=>lower(x.partnerId)).get(lower(partner))||{};}
function taskDue(t){return t.dueAt&&new Date(t.dueAt).getTime()<Date.now()&&!t.completed;}
function dealerLink(a){return `${ROOT}/dealer?partner=${encodeURIComponent(partnerKey(a))}`;}
function activityText(a){return `${a.action||a.type||"Activity"}${a.contextRef?` · ${a.contextRef}`:""}`;}
async function log(env,partner,action,contextType="dealer",contextRef="",details=""){await save(env,{id:id("KZAUD"),type:"admin-activity",partnerId:partner||"network",action,contextType,contextRef,details,actor:"KAIZURO Admin"});}

async function overview(request,env,ctx){const d=await data(env),taskMap=d["dealer-task"].filter(t=>!t.completed),overdue=taskMap.filter(taskDue),pending=d.application.filter(a=>!a.status||lower(a.status)==="pending"),openSupport=d.support.filter(s=>lower(s.status||"open")!=="resolved"),activeLeads=d.referral.filter(l=>!['won','lost'].includes(lower(l.status))),body=`<div class="kzv2-grid"><div class="kzv2-card"><small>Active dealers</small><strong>${d.account.filter(a=>lower(a.status||"active")==="active").length}</strong></div><div class="kzv2-card"><small>Needs attention</small><strong>${overdue.length+pending.length+openSupport.length}</strong></div><div class="kzv2-card"><small>Active leads</small><strong>${activeLeads.length}</strong></div><div class="kzv2-card"><small>Attributed revenue</small><strong>${money(d.sale.reduce((s,x)=>s+Number(x.amount||x.revenue||0),0))}</strong></div></div><div class="grid2"><section class="panel kzv2-section"><h2>What needs attention</h2><p>One queue for overdue work, pending applications and dealer friction.</p><div class="kzv2-list">${[...overdue.slice(0,5).map(t=>`<div class="kzv2-row kzv2-overdue"><small>${esc(day(t.dueAt))}</small><div><b>${esc(t.title)}</b><p>${esc(t.partnerName||t.partnerId)}</p></div><a class="btn light" href="${ROOT}/attention">Open</a></div>`),...pending.slice(0,3).map(a=>`<div class="kzv2-row"><small>Application</small><div><b>${esc(a.businessName||a.dealerName||a.email||"Dealer")}</b><p>Approval required</p></div><a class="btn light" href="${ROOT}/applications">Review</a></div>`),...openSupport.slice(0,3).map(s=>`<div class="kzv2-row"><small>Support</small><div><b>${esc(s.partnerName||s.partnerId)}</b><p>${esc(s.requestType||s.details||"")}</p></div><a class="btn light" href="${ROOT}/support">Open</a></div>`)].join("")||`<div class="kzv2-empty">No urgent items.</div>`}</div></section><section class="panel kzv2-section"><h2>Network activity</h2><p>Latest Admin and dealer events.</p><div class="kzv2-list">${d["admin-activity"].slice(0,8).map(a=>`<div class="kzv2-row"><small>${esc(fmt(a.createdAt))}</small><div><b>${esc(activityText(a))}</b><p>${esc(a.details||a.partnerId||"")}</p></div></div>`).join("")||`<div class="kzv2-empty">Activity will build as the team uses Admin V2.</div>`}</div></section></div>`;return render(request,env,ctx,{active:"overview",title:"Overview",heading:"Run the network,<br>not a spreadsheet.",copy:"Dealer operations, performance and action in one KAIZURO control layer.",body});}

async function attention(request,env,ctx){const d=await data(env),tasks=d["dealer-task"].filter(t=>!t.completed),overdue=tasks.filter(taskDue),pending=d.application.filter(a=>!a.status||lower(a.status)==="pending"),openSupport=d.support.filter(s=>lower(s.status||"open")!=="resolved"),alloc=d["allocation-request"].filter(a=>lower(a.status||"submitted")==="submitted"),body=`<div class="kzv2-grid"><div class="kzv2-card"><small>Overdue tasks</small><strong>${overdue.length}</strong></div><div class="kzv2-card"><small>Applications</small><strong>${pending.length}</strong></div><div class="kzv2-card"><small>Open support</small><strong>${openSupport.length}</strong></div><div class="kzv2-card"><small>Allocation review</small><strong>${alloc.length}</strong></div></div><section class="panel kzv2-section"><h2>Priority queue</h2><p>Start here each day.</p><div class="kzv2-list">${[...overdue.map(t=>`<div class="kzv2-row kzv2-overdue"><small>${esc(day(t.dueAt))}<br><span class="kzv2-priority-high">OVERDUE</span></small><div><b>${esc(t.title)}</b><p>${esc(t.partnerName||t.partnerId)} · ${esc(t.nextAction||"")}</p></div><a class="btn light" href="${ROOT}/dealer?partner=${encodeURIComponent(t.partnerId)}">Dealer</a></div>`),...pending.map(a=>`<div class="kzv2-row"><small>Application</small><div><b>${esc(a.businessName||a.dealerName||a.email||"Dealer")}</b><p>Pending review</p></div><a class="btn light" href="${ROOT}/applications">Review</a></div>`),...openSupport.map(s=>`<div class="kzv2-row"><small>Support</small><div><b>${esc(s.partnerName||s.partnerId)}</b><p>${esc(s.requestType||"")} · ${esc(s.details||"")}</p></div><a class="btn light" href="${ROOT}/support">Open</a></div>`),...alloc.map(a=>`<div class="kzv2-row"><small>Allocation</small><div><b>${esc(a.partnerName||a.partnerId)}</b><p>Awaiting approval</p></div><a class="btn light" href="${ROOT}/allocation">Review</a></div>`)].join("")||`<div class="kzv2-empty">Nothing needs immediate attention.</div>`}</div></section>`;return render(request,env,ctx,{active:"attention",title:"Attention",heading:"Know what matters<br>before it becomes urgent.",copy:"Overdue tasks, dealer applications, support and allocation exceptions in one queue.",body});}

async function dealers(request,env,ctx){const d=await data(env),metas=currentMap(d["dealer-meta"],x=>lower(x.partnerId)),tasks=d["dealer-task"],sales=d.sale,leads=d.referral,body=`<section class="panel kzv2-section"><h2>Dealer network</h2><p>Lifecycle, next action and performance at a glance.</p><div class="table-wrap"><table class="kzv2-table"><thead><tr><th>Dealer</th><th>Lifecycle</th><th>Tier</th><th>Next action</th><th>Leads</th><th>Orders</th><th>Revenue</th><th></th></tr></thead><tbody>${d.account.map(a=>{const p=partnerKey(a),m=metas.get(lower(p))||{},open=tasks.filter(t=>lower(t.partnerId)===lower(p)&&!t.completed).sort((x,y)=>String(x.dueAt||"").localeCompare(String(y.dueAt||"")))[0],ls=leads.filter(x=>lower(x.partnerId)===lower(p)||lower(x.partnerName)===lower(a.dealerName)),os=sales.filter(x=>lower(x.partnerId)===lower(p));return `<tr><td><a class="kzv2-anchor" href="${dealerLink(a)}">${esc(dealerName(a))}</a><br><small>${esc(a.contactName||"")} · ${esc(dealerEmail(a))}</small></td><td>${esc(m.lifecycle||a.status||"Active")}</td><td>${esc(m.tier||"Authorised Dealer")}</td><td>${open?`${esc(open.title)}<br><small>${esc(day(open.dueAt))}</small>`:"—"}</td><td>${ls.length}</td><td>${os.length}</td><td>${money(os.reduce((s,x)=>s+Number(x.amount||x.revenue||0),0))}</td><td><a class="btn light" href="${dealerLink(a)}">Open</a></td></tr>`}).join("")}</tbody></table></div></section>`;return render(request,env,ctx,{active:"dealers",title:"Dealers",heading:"One record for<br>every dealer relationship.",copy:"Commercial activity, tasks, communications, territory and performance connected to the dealer.",body});}

async function dealerProfile(request,env,ctx){const u=new URL(request.url),a=await accountFor(env,u.searchParams.get("partner")||"");if(!a)return resp("Dealer not found",404);const p=partnerKey(a),d=await data(env),m=metaFor(d["dealer-meta"],p),notes=d["dealer-note"].filter(x=>lower(x.partnerId)===lower(p)),tasks=d["dealer-task"].filter(x=>lower(x.partnerId)===lower(p)),onMap=currentMap(d["dealer-onboarding"],x=>`${lower(x.partnerId)}|${lower(x.item)}`),docs=d["dealer-document"].filter(x=>lower(x.partnerId)===lower(p)),comms=d["dealer-communication"].filter(x=>lower(x.partnerId)===lower(p)),acts=d["admin-activity"].filter(x=>lower(x.partnerId)===lower(p)),leads=d.referral.filter(x=>lower(x.partnerId)===lower(p)||lower(x.partnerName)===lower(a.dealerName)),orders=d.sale.filter(x=>lower(x.partnerId)===lower(p)),alloc=d["allocation-request"].filter(x=>lower(x.partnerId)===lower(p)),support=d.support.filter(x=>lower(x.partnerId)===lower(p)),won=leads.filter(x=>lower(x.status)==="won").length,revenue=orders.reduce((s,x)=>s+Number(x.amount||x.revenue||0),0),complete=ONBOARD.filter(item=>onMap.get(`${lower(p)}|${lower(item)}`)?.completed).length,pct=Math.round(complete/ONBOARD.length*100),next=tasks.filter(t=>!t.completed).sort((x,y)=>String(x.dueAt||"").localeCompare(String(y.dueAt||"")))[0];
const body=`<div class="kzv2-toolbar"><a class="btn" href="${ROOT}/email?partner=${encodeURIComponent(p)}&context=dealer">Email dealer</a><a class="btn light" href="#task">Add task</a><a class="btn light" href="#note">Add note</a><a class="btn light" href="${ROOT}/dealers">Back</a></div><div class="kzv2-grid"><div class="kzv2-card"><small>Lifecycle</small><strong style="font-size:20px">${esc(m.lifecycle||a.status||"Active")}</strong></div><div class="kzv2-card"><small>Next action</small><strong style="font-size:16px">${esc(next?.title||"None")}</strong><span class="kzv2-muted">${next?.dueAt?esc(day(next.dueAt)):""}</span></div><div class="kzv2-card"><small>Revenue</small><strong>${money(revenue)}</strong></div><div class="kzv2-card"><small>Lead conversion</small><strong>${leads.length?Math.round(won/leads.length*100):0}%</strong></div></div>
<div class="grid2"><section class="panel kzv2-section"><h2>${esc(dealerName(a))}</h2><p>${esc(a.contactName||"")} · ${esc(dealerEmail(a))}<br>${esc(a.assignedPartnerId||"")} · ${esc(a.referralCode||a.partnerCode||"")}</p><form class="kzv2-form" method="post" action="${ROOT}/dealer/meta"><input type="hidden" name="partner" value="${esc(p)}"><div class="kzv2-two"><label>Lifecycle<select name="lifecycle">${LIFECYCLE.map(x=>`<option ${x===(m.lifecycle||a.status)?"selected":""}>${x}</option>`).join("")}</select></label><label>Dealer tier<select name="tier">${TIERS.map(x=>`<option ${x===(m.tier||"Authorised Dealer")?"selected":""}>${x}</option>`).join("")}</select></label></div><div class="kzv2-two"><label>Territory<input name="territory" value="${esc(m.territory||a.region||a.location||"")}"></label><label>Exclusivity<select name="exclusive"><option ${m.exclusive==="No"?"selected":""}>No</option><option ${m.exclusive==="Yes"?"selected":""}>Yes</option><option ${m.exclusive==="Review"?"selected":""}>Review</option></select></label></div><label>Territory notes<textarea name="territoryNotes">${esc(m.territoryNotes||"")}</textarea></label><button class="btn" type="submit">Save dealer profile</button></form></section><section class="panel kzv2-section"><h2>Onboarding</h2><p>${complete}/${ONBOARD.length} complete · ${pct}%</p><div class="kzv2-progress"><span style="width:${pct}%"></span></div><form method="post" action="${ROOT}/dealer/onboarding"><input type="hidden" name="partner" value="${esc(p)}">${ONBOARD.map(item=>{const done=!!onMap.get(`${lower(p)}|${lower(item)}`)?.completed;return `<label class="kzv2-check"><input type="checkbox" name="item" value="${esc(item)}" ${done?"checked":""}>${esc(item)}</label>`}).join("")}<button class="btn" type="submit" style="margin-top:12px">Save onboarding</button></form></section></div>
<div class="grid2"><section class="panel kzv2-section" id="task"><h2>Tasks + next actions</h2><form class="kzv2-form" method="post" action="${ROOT}/dealer/task"><input type="hidden" name="partner" value="${esc(p)}"><label>Task / next action<input name="title" required placeholder="Call dealer — discuss HALO allocation"></label><div class="kzv2-two"><label>Due date<input type="date" name="dueAt" required></label><label>Priority<select name="priority"><option>Normal</option><option>High</option><option>Low</option></select></label></div><label>Assigned to<input name="owner" value="KAIZURO"></label><button class="btn" type="submit">Add task</button></form><div class="kzv2-list">${tasks.map(t=>`<div class="kzv2-row ${taskDue(t)?"kzv2-overdue":""}"><small>${esc(day(t.dueAt))}<br>${esc(t.priority||"Normal")}</small><div><b>${esc(t.title)}</b><p>${esc(t.owner||"KAIZURO")}</p></div>${t.completed?`<span class="kzv2-pill green">Done</span>`:`<form method="post" action="${ROOT}/dealer/task/complete"><input type="hidden" name="partner" value="${esc(p)}"><input type="hidden" name="task" value="${esc(t.id)}"><button class="btn light">Complete</button></form>`}</div>`).join("")||`<div class="kzv2-empty">No tasks yet.</div>`}</div></section><section class="panel kzv2-section" id="note"><h2>Internal notes</h2><form class="kzv2-form" method="post" action="${ROOT}/dealer/note"><input type="hidden" name="partner" value="${esc(p)}"><label>Note<textarea name="note" required placeholder="Call notes, objections, product feedback, next steps…"></textarea></label><button class="btn" type="submit">Add note</button></form><div class="kzv2-list">${notes.map(n=>`<div class="kzv2-row"><small>${esc(fmt(n.createdAt))}</small><div><b>${esc(n.author||"KAIZURO")}</b><p>${esc(n.note)}</p></div></div>`).join("")||`<div class="kzv2-empty">No internal notes.</div>`}</div></section></div>
<div class="kzv2-grid"><div class="kzv2-card"><small>Leads</small><strong>${leads.length}</strong></div><div class="kzv2-card"><small>Orders</small><strong>${orders.length}</strong></div><div class="kzv2-card"><small>Allocations</small><strong>${alloc.length}</strong></div><div class="kzv2-card"><small>Support</small><strong>${support.length}</strong></div></div>
<div class="grid2"><section class="panel kzv2-section"><h2>Documents</h2><form class="kzv2-form" method="post" action="${ROOT}/dealer/document"><input type="hidden" name="partner" value="${esc(p)}"><label>Document name<input name="title" required placeholder="Dealer agreement"></label><label>Link / reference<input name="url" placeholder="https://… or internal reference"></label><button class="btn" type="submit">Add document</button></form><div class="kzv2-list">${docs.map(x=>`<div class="kzv2-row"><small>${esc(day(x.createdAt))}</small><div><b>${esc(x.title)}</b><p>${esc(x.url||"Stored reference")}</p></div>${x.url?`<a class="btn light" target="_blank" href="${esc(x.url)}">Open</a>`:""}</div>`).join("")||`<div class="kzv2-empty">No documents linked.</div>`}</div></section><section class="panel kzv2-section"><h2>Communications + activity</h2><div class="kzv2-list">${[...comms.map(x=>({...x,_kind:"Email"})),...acts.map(x=>({...x,_kind:"Activity"}))].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,20).map(x=>`<div class="kzv2-row"><small>${esc(fmt(x.createdAt))}<br>${esc(x._kind)}</small><div><b>${esc(x.subject||x.action||"Update")}</b><p>${esc(x.contextRef||x.details||"")}</p></div></div>`).join("")||`<div class="kzv2-empty">No activity yet.</div>`}</div></section></div>`;
return render(request,env,ctx,{active:"dealers",title:"Dealer Profile",heading:`${esc(dealerName(a))}`,copy:"The complete KAIZURO relationship: people, performance, tasks, territory, onboarding and history.",body});}

async function applications(request,env,ctx){const d=await data(env),decisions=currentMap(d["application-decision"],x=>String(x.applicationId)),body=`<section class="panel kzv2-section"><h2>Dealer applications</h2><p>Approve, request information or decline without leaving Admin.</p><div class="table-wrap"><table class="kzv2-table"><thead><tr><th>Applicant</th><th>Region</th><th>Type</th><th>Status</th><th>Submitted</th><th>Action</th></tr></thead><tbody>${d.application.map(a=>{const ds=decisions.get(String(a.id)),st=ds?.status||a.status||"Pending";return `<tr><td><b>${esc(a.businessName||a.dealerName||a.contactName||a.email||"Dealer")}</b><br><small>${esc(a.email||"")}</small></td><td>${esc(a.region||a.location||"")}</td><td>${esc(a.partnerType||"Dealer")}</td><td><span class="kzv2-pill ${st==="Approved"?"green":st==="Declined"?"red":""}">${esc(st)}</span></td><td>${esc(day(a.createdAt))}</td><td><form class="kzv2-actions" method="post" action="${ROOT}/applications/decision"><input type="hidden" name="application" value="${esc(a.id)}"><input type="hidden" name="partner" value="${esc(a.partnerId||a.email||"")}"><select name="status">${APP_STATES.map(x=>`<option ${x===st?"selected":""}>${x}</option>`).join("")}</select><button class="btn">Save</button></form></td></tr>`}).join("")||`<tr><td colspan="6">No applications yet.</td></tr>`}</tbody></table></div></section>`;return render(request,env,ctx,{active:"applications",title:"Applications",heading:"Move the right dealers<br>into the network faster.",copy:"Application decisions, onboarding handoff and dealer status in one workflow.",body});}

async function inventory(request,env,ctx){const d=await data(env),products=currentMap(d["product-config"],x=>lower(x.product)),alloc=d["allocation-request"],cards=["ASSAULT PE6-8","HALO PE10-12"].map(name=>{const p=products.get(lower(name))||products.get(lower(name.split(" ")[0]))||{},req=alloc.filter(a=>lower(a.product||a.productInterest).includes(lower(name.split(" ")[0]))),reserved=req.filter(a=>["approved","reserved"].includes(lower(a.status))).reduce((s,a)=>s+Number(a.quantity||0),0);return `<div class="kzv2-card"><small>${esc(name)}</small><strong>${p.available??"—"}</strong><span class="kzv2-muted">Available · ${reserved} reserved · ${p.incoming??"—"} incoming</span></div>`}).join("");const body=`<div class="kzv2-grid">${cards}<div class="kzv2-card"><small>Allocation requests</small><strong>${alloc.length}</strong></div><div class="kzv2-card"><small>Production status</small><strong style="font-size:18px">${[...products.values()][0]?.stockStatus||"Not configured"}</strong></div></div><section class="panel kzv2-section"><h2>Inventory + production control</h2><p>This screen uses central product configuration and real dealer allocation requests. It does not invent stock.</p><div class="table-wrap"><table class="kzv2-table"><thead><tr><th>Product</th><th>Available</th><th>Incoming</th><th>ETA / note</th><th>Status</th></tr></thead><tbody>${["ASSAULT","HALO"].map(n=>{const p=products.get(lower(n))||{};return `<tr><td><b>${n}</b></td><td>${p.available??"Not configured"}</td><td>${p.incoming??"Not configured"}</td><td>${esc(p.eta||p.note||"—")}</td><td>${esc(p.stockStatus||"Not configured")}</td></tr>`}).join("")}</tbody></table></div></section>`;return render(request,env,ctx,{active:"inventory",title:"Inventory",heading:"Know what is available,<br>committed and coming.",copy:"Dealer allocation, central stock configuration and production signals without fake inventory.",body});}

async function territories(request,env,ctx){const d=await data(env),metas=currentMap(d["dealer-meta"],x=>lower(x.partnerId)),body=`<section class="panel kzv2-section"><h2>Dealer territories</h2><p>Region, territory and exclusivity status across the network.</p><div class="table-wrap"><table class="kzv2-table"><thead><tr><th>Dealer</th><th>Country / region</th><th>Territory</th><th>Exclusivity</th><th>Notes</th></tr></thead><tbody>${d.account.map(a=>{const m=metas.get(lower(partnerKey(a)))||{};return `<tr><td><a class="kzv2-anchor" href="${dealerLink(a)}">${esc(dealerName(a))}</a></td><td>${esc(a.region||a.location||"—")}</td><td>${esc(m.territory||"—")}</td><td>${esc(m.exclusive||"No")}</td><td>${esc(m.territoryNotes||"—")}</td></tr>`}).join("")}</tbody></table></div></section>`;return render(request,env,ctx,{active:"territories",title:"Territories",heading:"Protect the network<br>as it expands.",copy:"See territory ownership, exclusivity and market overlap before approving the next dealer.",body});}

async function activity(request,env,ctx){const d=await data(env),events=[...d["admin-activity"],...d["dealer-communication"].map(x=>({...x,action:`Email · ${x.subject||"Dealer update"}`,details:x.to||""}))].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),body=`<section class="panel kzv2-section"><h2>Network audit log</h2><p>Who did what, when, and against which dealer or record.</p><div class="kzv2-list">${events.map(x=>`<div class="kzv2-row"><small>${esc(fmt(x.createdAt))}</small><div><b>${esc(x.action||x.type)}</b><p>${esc(x.partnerName||x.partnerId||"")}${x.details?` · ${esc(x.details)}`:""}</p></div><span class="kzv2-pill">${esc(x.actor||"KAIZURO")}</span></div>`).join("")||`<div class="kzv2-empty">No activity yet.</div>`}</div></section>`;return render(request,env,ctx,{active:"activity",title:"Activity",heading:"Every commercial action,<br>visible and accountable.",copy:"A network-wide audit trail for dealer management and internal coordination.",body});}

async function leadDetail(request,env,ctx){const u=new URL(request.url),ref=u.searchParams.get("ref")||"",d=await data(env),lead=d.referral.find(x=>String(x.id)===ref);if(!lead)return resp("Lead not found",404);const meta=currentMap(d["lead-admin-meta"],x=>String(x.leadRef)).get(ref)||{},body=`<div class="kzv2-toolbar"><a class="btn light" href="${ROOT}/leads">Back to leads</a></div><div class="grid2"><section class="panel kzv2-section"><h2>Lead ${esc(ref)}</h2><p>${esc(lead.customerName||"Customer")} · ${esc(lead.customerEmail||lead.customerMobile||"")}<br>${esc(lead.productInterest||"")} · ${esc(lead.targetSpecies||"")}</p></section><section class="panel kzv2-section"><h2>KAIZURO CRM</h2><form class="kzv2-form" method="post" action="${ROOT}/lead/meta"><input type="hidden" name="lead" value="${esc(ref)}"><input type="hidden" name="partner" value="${esc(lead.partnerId||"")}"><div class="kzv2-two"><label>Next follow-up<input type="date" name="followUpAt" value="${esc(meta.followUpAt||"")}"></label><label>Assigned owner<input name="owner" value="${esc(meta.owner||"KAIZURO")}"></label></div><label>Next action<input name="nextAction" value="${esc(meta.nextAction||"")}"></label><div class="kzv2-two"><label>Expected sale value<input type="number" min="0" name="expectedValue" value="${esc(meta.expectedValue||"")}"></label><label>Lead source<input name="source" value="${esc(meta.source||lead.source||"")}"></label></div><label>Lost reason<input name="lostReason" value="${esc(meta.lostReason||"")}"></label><label>Internal notes<textarea name="notes">${esc(meta.notes||"")}</textarea></label><button class="btn">Save lead CRM</button></form></section></div>`;return render(request,env,ctx,{active:"leads",title:"Lead CRM",heading:"Turn lead activity<br>into a managed next action.",copy:"Follow-up, ownership, value, source and internal context linked to the lead.",body});}

async function post(request,env,ctx,path){if(!validOrigin(request)||!(await authed(request,env,ctx)))return resp("Unauthorized",403);const f=await request.formData();
 if(path==="dealer/meta"){const partner=String(f.get("partner")||""),a=await accountFor(env,partner);if(!a)return resp("Dealer not found",404);const p=partnerKey(a);await save(env,{id:id("KZDM"),type:"dealer-meta",partnerId:p,partnerName:dealerName(a),lifecycle:String(f.get("lifecycle")||"Active"),tier:String(f.get("tier")||"Authorised Dealer"),territory:String(f.get("territory")||""),exclusive:String(f.get("exclusive")||"No"),territoryNotes:String(f.get("territoryNotes")||"")});await log(env,p,"Dealer profile updated","dealer",p);return redir(request,`${ROOT}/dealer?partner=${encodeURIComponent(p)}`)}
 if(path==="dealer/task"){const partner=String(f.get("partner")||""),a=await accountFor(env,partner);if(!a)return resp("Dealer not found",404);const p=partnerKey(a);const t={id:id("KZT"),type:"dealer-task",partnerId:p,partnerName:dealerName(a),title:String(f.get("title")||"").trim(),nextAction:String(f.get("title")||"").trim(),dueAt:String(f.get("dueAt")||""),priority:String(f.get("priority")||"Normal"),owner:String(f.get("owner")||"KAIZURO"),completed:false};if(!t.title)return resp("Task required",400);await save(env,t);await log(env,p,"Task added","task",t.id,t.title);return redir(request,`${ROOT}/dealer?partner=${encodeURIComponent(p)}#task`)}
 if(path==="dealer/task/complete"){const partner=String(f.get("partner")||""),task=String(f.get("task")||""),a=await accountFor(env,partner);if(!a)return resp("Dealer not found",404);const rows=await all(env,"dealer-task"),old=rows.find(x=>x.id===task);if(old)await save(env,{...old,completed:true,completedAt:now(),createdAt:now()});await log(env,partner,"Task completed","task",task,old?.title||"");return redir(request,`${ROOT}/dealer?partner=${encodeURIComponent(partner)}#task`)}
 if(path==="dealer/note"){const partner=String(f.get("partner")||""),a=await accountFor(env,partner);if(!a)return resp("Dealer not found",404);const p=partnerKey(a),note=String(f.get("note")||"").trim();if(!note)return resp("Note required",400);await save(env,{id:id("KZN"),type:"dealer-note",partnerId:p,partnerName:dealerName(a),note,author:"KAIZURO Admin"});await log(env,p,"Internal note added","note","",note.slice(0,120));return redir(request,`${ROOT}/dealer?partner=${encodeURIComponent(p)}#note`)}
 if(path==="dealer/onboarding"){const partner=String(f.get("partner")||""),a=await accountFor(env,partner);if(!a)return resp("Dealer not found",404);const p=partnerKey(a),checked=new Set(f.getAll("item").map(String));for(const item of ONBOARD)await save(env,{id:id("KZON"),type:"dealer-onboarding",partnerId:p,partnerName:dealerName(a),item,completed:checked.has(item)});await log(env,p,"Onboarding checklist updated","onboarding",p);return redir(request,`${ROOT}/dealer?partner=${encodeURIComponent(p)}`)}
 if(path==="dealer/document"){const partner=String(f.get("partner")||""),a=await accountFor(env,partner);if(!a)return resp("Dealer not found",404);const p=partnerKey(a),title=String(f.get("title")||"").trim(),url=String(f.get("url")||"").trim();if(!title)return resp("Document name required",400);await save(env,{id:id("KZDOC"),type:"dealer-document",partnerId:p,partnerName:dealerName(a),title,url});await log(env,p,"Document linked","document","",title);return redir(request,`${ROOT}/dealer?partner=${encodeURIComponent(p)}`)}
 if(path==="applications/decision"){const application=String(f.get("application")||""),partner=String(f.get("partner")||""),status=String(f.get("status")||"Pending");if(!APP_STATES.includes(status))return resp("Invalid status",400);await save(env,{id:id("KZAPPD"),type:"application-decision",partnerId:partner||"application",applicationId:application,status,actor:"KAIZURO Admin"});await log(env,partner||"network",`Application ${status}`,"application",application);return redir(request,`${ROOT}/applications`)}
 if(path==="lead/meta"){const lead=String(f.get("lead")||""),partner=String(f.get("partner")||"");await save(env,{id:id("KZLM"),type:"lead-admin-meta",partnerId:partner||"network",leadRef:lead,followUpAt:String(f.get("followUpAt")||""),owner:String(f.get("owner")||"KAIZURO"),nextAction:String(f.get("nextAction")||""),expectedValue:Number(f.get("expectedValue")||0),source:String(f.get("source")||""),lostReason:String(f.get("lostReason")||""),notes:String(f.get("notes")||"")});await log(env,partner||"network","Lead CRM updated","lead",lead);return redir(request,`${ROOT}/lead?ref=${encodeURIComponent(lead)}`)}
 return null;}

export default {async fetch(request,env,ctx){const u=new URL(request.url),host=u.hostname.toLowerCase(),path=u.pathname.replace(/\/$/,"");if(!HOSTS.has(host)||!path.startsWith(ROOT))return app.fetch(request,env,ctx);
 if(request.method==="POST"){const sub=path.slice(ROOT.length+1);const r=await post(request,env,ctx,sub);if(r)return r;return app.fetch(request,env,ctx)}
 if(request.method!=="GET")return app.fetch(request,env,ctx);if(!(await authed(request,env,ctx)))return app.fetch(request,env,ctx);
 if(path===ROOT||path===`${ROOT}/overview`)return overview(request,env,ctx);if(path===`${ROOT}/attention`)return attention(request,env,ctx);if(path===`${ROOT}/dealers`)return dealers(request,env,ctx);if(path===`${ROOT}/dealer`)return dealerProfile(request,env,ctx);if(path===`${ROOT}/applications`)return applications(request,env,ctx);if(path===`${ROOT}/inventory`)return inventory(request,env,ctx);if(path===`${ROOT}/territories`)return territories(request,env,ctx);if(path===`${ROOT}/activity`)return activity(request,env,ctx);if(path===`${ROOT}/lead`)return leadDetail(request,env,ctx);
 const response=await app.fetch(request,env,ctx);if(response.status===200&&(response.headers.get("Content-Type")||"").includes("text/html")){const c=await counts(env);let active=path.split("/").pop()||"overview";return new HTMLRewriter().on("head",{element(e){e.append(styles(),{html:true})}}).on("aside nav",{element(e){e.setInnerContent(nav(c,active),{html:true})}}).transform(response)}return response;}};
